const data=[
{id:"REC-101",source:"dept_records_idx",category:"Database",records:4820,latency:14.2,status:"Optimized"},
{id:"REC-102",source:"csv_batch_ingest",category:"Pipeline",records:8200,latency:38.6,status:"Standard"},
{id:"REC-103",source:"null_imputer_clean",category:"Automation",records:3450,latency:11.5,status:"Optimized"},
{id:"REC-104",source:"b_tree_join_eval",category:"Database",records:6100,latency:19.8,status:"Optimized"},
{id:"REC-105",source:"json_schema_normalizer",category:"Automation",records:5120,latency:24.1,status:"Standard"},
{id:"REC-106",source:"daily_rollup_agg",category:"Pipeline",records:9400,latency:29.4,status:"Optimized"}];
const projects=[
{n:"01",title:"Automated Data Pipeline & Cleansing Engine",tag:"Python-driven automation for multi-source data ingestion and structured validation.",cat:"Data Automation & Scripting",problem:"Raw operational datasets frequently arrive in inconsistent formats with missing attributes, duplicate records, and unstructured fields, requiring significant manual clean-up time.",approach:"Engineered a modular Python pipeline that automates CSV and JSON ingestion, validates schema rules, handles null imputation, and exports cleaned tabular summaries for reporting.",outcome:"Eliminates repetitive manual preprocessing, standardizes tabular records into relational-ready schemas, and exports structured summaries for downstream analysis.",tags:["Python","Automation","Data Cleansing","ETL Logic"],metrics:[["Ingestion Modality","Multi-Format"],["Execution Flow","Deterministic"],["Output","Relational-Ready"]],lang:"python",caption:"Modular data validation and transformation step",code:`def process_records(raw_dataset: list[dict]) -> list[dict]:\n    \"\"\"Cleanses incoming records and enforces schema integrity.\"\"\"\n    cleaned = []\n    for item in raw_dataset:\n        if not item.get(\"id\") or item.get(\"value\") is None:\n            continue  # Filter malformed records\n        cleaned.append({\n            \"id\": int(item[\"id\"]),\n            \"metric\": float(item[\"value\"]),\n            \"status\": item.get(\"status\", \"ACTIVE\").strip().upper()\n        })\n    return sorted(cleaned, key=lambda x: x[\"metric\"], reverse=True)`},
{n:"02",title:"Relational DBMS Query & Indexing Analysis",tag:"Empirical study comparing indexing strategies and join behaviors on relational schemas.",cat:"Database Systems & Research",problem:"Unindexed queries on growing relational tables suffer exponential latency degradation due to repetitive full-table scans and unoptimized join paths.",approach:"Formulated test schemas modeling realistic transactional relationships. Tested execution plans (EXPLAIN ANALYZE) across clustered indexes, composite B-tree indexes, and selective multi-table joins.",outcome:"Documented measurable query execution gains when switching from sequential scan patterns to indexed lookups, highlighting the critical role of foreign key indexing.",tags:["SQL","DBMS","Index Design","Query Optimization"],metrics:[["Evaluation Method","EXPLAIN Plan"],["Index Architecture","B-Tree & Composite"],["Focus","Query Cost Reduction"]],lang:"sql",caption:"Analytical join with composite indexing target",code:`-- Optimized analytical query targeting indexed composite fields\nSELECT \n    d.department_name,\n    COUNT(e.emp_id) AS total_records,\n    ROUND(AVG(e.performance_score), 2) AS avg_score\nFROM departments d\nINNER JOIN employees e \n    ON d.dept_id = e.dept_id\nWHERE e.status = 'ACTIVE' AND e.join_year >= 2022\nGROUP BY d.department_name\nORDER BY avg_score DESC;`},
{n:"03",title:"Interactive Exploratory Data Dashboard",tag:"Responsive analytical interface with dynamic filtering, statistical rollups, and live charting.",cat:"Interactive Analytics & Frontend",problem:"Static data tables make it difficult for stakeholders to intuitively spot trends, filter categorical attributes, and extract instant summary insights.",approach:"Built a responsive, zero-latency analytical dashboard interface with dynamic client-side filtering, dimensional breakdown, and interactive visual data representations.",outcome:"Empowers users to isolate key segments, inspect distribution metrics, and observe live updates without server round-trips.",tags:["Analytics","Data Filtering","Interactive UI","Data Structures"],metrics:[["Update Latency","< 16ms"],["Dimension Support","Multi-Filter"],["UI Paradigm","Live Reactive"]],lang:"javascript",caption:"Client-side multi-variable aggregation",code:`function aggregateData(records, filter) {\n  const filtered = filter === 'ALL'\n    ? records\n    : records.filter(r => r.category === filter);\n  const total = filtered.reduce((acc, curr) => acc + curr.value, 0);\n  const avg = filtered.length ? Math.round(total / filtered.length) : 0;\n  return { count: filtered.length, total, avg };\n}`}
];
function renderSandbox(){
 const cat=document.querySelector(".filter.active")?.dataset.cat||"All";
 const opt=document.getElementById("optimizedBtn")?.classList.contains("on");
 const sort=document.getElementById("sortSelect")?.value||"latency";
 let rows=data.filter(x=>(cat==="All"||x.category===cat)&&(!opt||x.status==="Optimized"));
 rows.sort((a,b)=>sort==="latency"?a.latency-b.latency:b.records-a.records);
 const total=rows.reduce((s,x)=>s+x.records,0), avg=rows.length?(rows.reduce((s,x)=>s+x.latency,0)/rows.length).toFixed(1):"0.0", eff=rows.length?Math.round(rows.filter(x=>x.status==="Optimized").length/rows.length*100):0;
 const max=45;
 document.getElementById("sandbox").innerHTML=`<div class="sb-head"><span><span class="lights"><i></i><i></i><i></i></span>analytical_sandbox.js</span><span class="live">● Interactive Live State</span></div>
 <div class="sb-pipeline"><span>PIPELINE:</span>${["Raw Data","Filter","Analyze","Live Insight"].map((x,i)=>`<button class="step ${i===3?"insight ":""}${i===3?"active":""}" data-step="${i}">0${i+1}. ${x}</button>`).join("")}</div>
 <div class="sb-controls"><div class="filters"><span>Category:</span>${["All","Database","Pipeline","Automation"].map(x=>`<button class="filter ${cat===x?"active":""}" data-cat="${x}">${x}</button>`).join("")}</div><div>Sort: <select id="sortSelect" class="sort"><option value="latency" ${sort==="latency"?"selected":""}>Latency</option><option value="records" ${sort==="records"?"selected":""}>Records</option></select> <button id="optimizedBtn" class="status ${opt?"on":""}">${opt?"✓ Optimized Only":"Status: All"}</button></div></div>
 <div class="metrics"><div class="metric"><small>TOTAL RECORDS</small><b>${total.toLocaleString()}</b></div><div class="metric bluev"><small>AVG LATENCY</small><b>${avg} <small>ms</small></b></div><div class="metric greenv"><small>EFFICIENCY RATIO</small><b>${eff}% <small>opt</small></b></div></div>
 <div class="sb-body"><div class="chart-title"><span>▥ Execution Latency Benchmark (ms)</span><span>Showing ${rows.length} records</span></div>${rows.map(x=>`<div class="bar-row"><div class="bar-meta"><span class="bar-name">${x.id} &nbsp; ${x.source} &nbsp; <small>${x.category}</small></span><span>${x.records.toLocaleString()} rows &nbsp; <b>${x.latency} ms</b></span></div><div class="bar-track"><div class="bar ${x.status==="Standard"?"standard":""}" style="width:${Math.max(x.latency/max*100,10)}%"></div></div></div>`).join("")}</div>
 <div class="sb-footer"><span>✓ Interactive data state compiled locally via JavaScript</span><button class="reset" id="resetSandbox">↻ Reset</button></div>`;
 document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSandbox()});
 document.getElementById("sortSelect").onchange=renderSandbox; document.getElementById("optimizedBtn").onclick=()=>{document.getElementById("optimizedBtn").classList.toggle("on");renderSandbox()}; document.getElementById("resetSandbox").onclick=()=>renderSandbox();
 document.querySelectorAll(".step").forEach(b=>b.onclick=()=>{document.querySelectorAll(".step").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
}
function renderProjects(){document.getElementById("projects").innerHTML=projects.map((p,i)=>`<article class="project card"><div class="project-head"><div><span class="project-num">PROJECT ${p.n}</span> <span class="mono muted">${p.cat}</span></div><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join("")}</div></div><div class="project-body"><h3>${p.title}</h3><div class="tagline">${p.tag}</div><div class="problem-grid"><div><small>THE PROBLEM</small><p>${p.problem}</p></div><div><small>THE TECHNICAL APPROACH</small><p>${p.approach}</p></div></div><div class="outcome"><small>PRACTICAL OUTCOME & VALUE</small><p>${p.outcome}</p></div><div class="metrics-row">${p.metrics.map(m=>`<div><small>${m[0]}</small><b>${m[1]}</b></div>`).join("")}</div><div class="code-toggle"><button class="code-btn" data-index="${i}">⌘ <span>Inspect Code Logic</span>⌄</button><button class="copy-btn" data-index="${i}">Copy snippet</button></div><div class="codebox" id="code-${i}"><div class="codehead"><span>${p.caption}</span><span>${p.lang}</span></div><pre>${escapeHtml(p.code)}</pre></div></div></article>`).join("");
 document.querySelectorAll(".code-btn").forEach(b=>b.onclick=()=>{const box=document.getElementById("code-"+b.dataset.index);box.classList.toggle("open");b.querySelector("span").textContent=box.classList.contains("open")?"Hide Code Implementation":"Inspect Code Logic"});
 document.querySelectorAll(".copy-btn").forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(projects[b.dataset.index].code);b.textContent="Copied ✓";setTimeout(()=>b.textContent="Copy snippet",1500)});
}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
document.addEventListener("DOMContentLoaded",()=>{
 renderSandbox();renderProjects();
 const nav=document.getElementById("navbar");addEventListener("scroll",()=>nav.classList.toggle("scrolled",scrollY>20),{passive:true});
 const menu=document.getElementById("mobileMenu");document.getElementById("menuBtn").onclick=()=>menu.classList.toggle("open");
 document.querySelectorAll("a[href^='#']").forEach(a=>a.addEventListener("click",()=>menu.classList.remove("open")));
 const modal=document.getElementById("resumeModal");document.querySelectorAll("[data-open-resume]").forEach(b=>b.onclick=()=>{modal.classList.add("open");modal.setAttribute("aria-hidden","false")});document.getElementById("closeModal").onclick=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true")};modal.onclick=e=>{if(e.target===modal)document.getElementById("closeModal").click()};document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("closeModal").click()});
 document.getElementById("copyEmail").onclick=async()=>{await navigator.clipboard.writeText("krishna.connect.tech@gmail.com");document.getElementById("copyEmail").textContent="Copied ✓";setTimeout(()=>document.getElementById("copyEmail").textContent="Copy Address",1600)};
 document.getElementById("contactForm").onsubmit=e=>{e.preventDefault();const n=document.getElementById("senderName").value,em=document.getElementById("senderEmail").value,m=document.getElementById("message").value;location.href=`mailto:krishna.connect.tech@gmail.com?subject=${encodeURIComponent("Portfolio inquiry from "+n)}&body=${encodeURIComponent("Name: "+n+"\nEmail: "+em+"\n\n"+m)}`};
 document.getElementById("topBtn").onclick=()=>scrollTo({top:0,behavior:"smooth"});
});
